version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: monthly
    groups:
      python-dependencies:
        patterns: ["*"]
    assignees: ["MihaelaAghirculesei"]
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ["*"]
    assignees: ["MihaelaAghirculesei"]
    commit-message:
      prefix: "ci(deps)"
